# Generated by Django 5.0.7 on 2024-07-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="cover_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/users/cover_photos"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/users/profile_pictures"
            ),
        ),
    ]
