# Generated by Django 5.0.7 on 2024-09-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_userprofile_cover_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="address",
            new_name="address_line_1",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
