# Generated by Django 5.0.7 on 2024-11-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_alter_category_options_fooditem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="image",
            field=models.ImageField(
                default="foodimages/default_food.jpg", upload_to="foodimages"
            ),
        ),
    ]
