# Generated by Django 5.0.7 on 2024-11-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0003_alter_fooditem_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
